#!/usr/bin/env zsh

## if [[ -z $STOW_FOLDERS ]]; then
##     # STOW_FOLDERS="bin,i3,netflix,nvim,personal,tmux,uwuntu,xkb,zsh"
##     STOW_FOLDERS=".bin,.config,.oh-my-zsh,home"
## fi
## if [[ -z $DOTFILES ]]; then
##     DOTFILES=$HOME/.dotfiles
## fi
## 
## pushd $DOTFILES
## for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
## do
##     echo "stow $folder"
##     stow -D $folder
##     stow $folder
## done
## popd
#
stow -D .
stow .
