#!/bin/zsh

SOURCE_DIR="$HOME/notes/hippo"
DEST_DIR="$HOME/notes/cortex"

if [ -z "$1" ]; then
    find "$SOURCE_DIR" -type f -name "*.md" | while read -r file; do
      # echo "Processing $file"
      # Extract the tag from the file. This assumes the tag is on the line immediately following "tag:"
      tag=$(awk '/tag:/{getline; print; exit}' "$file" | sed -e 's/^ *- *//' -e 's/^ *//;s/ *$//')

      # echo "Found tag $tag"

      # If a tag is found, proceed with moving the file
      if [ ! -z "$tag" ]; then
        # Create the target directory if it doesn't exist
        TARGET_DIR="$DEST_DIR/$tag"
        mkdir -p "$TARGET_DIR"

        # Move the file to the target directory
        mv "$file" "$TARGET_DIR/"
        # echo "Moved $file to $TARGET_DIR"
      # else
      #   echo "No tag found for $file"
      fi

    done
else
    file="$1"
    tag=$(awk '/tag:/{getline; print; exit}' "$file" | sed -e 's/^ *- *//' -e 's/^ *//;s/ *$//')
    if [ ! -z "$tag" ]; then
      TARGET_DIR="$DEST_DIR/$tag"
      mkdir -p "$TARGET_DIR"
      mv "$file" "$TARGET_DIR/"
    fi
fi
# echo "Done 🪷"

