#!/bin/zsh

if [ -z "$1" ]; then
  echo "Error: A file name must be set."
  exit 1
fi

file_name=$(echo "$1" | tr ' ' '-')
formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
cd "$NOTES_FOLDER" || exit
touch "hippo/${formatted_file_name}"
nvim "hippo/${formatted_file_name}"
