[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[font]
size = 16.0
normal = { family = "Hack Nerd Font", style = "Regular" }
