#!/bin/sh

while getopts 'L:m:p::' opt; do
    case $opt in
        L)
            [[ $OPTARG =~ ^[0-9]+$ ]] || error "${opt}: ${OPTARG} is not a number" 2
            UPPER_LIMIT="${OPTARG}"
            ;;
        m)
            MESSAGE="${OPTARG}"
            ;;
        p)
            [[ $OPTARG =~ ^[0-9]+$ ]] || error "${opt}: ${OPTARG} is not a number" 2
            POLL="${OPTARG}"
            ;;
        :)
            error "Option -$OPTARG requires an argument." 2
            ;;
        \?)
            exit 2
            ;;
    esac
done
CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
PREVIOUS_CAPACITY=$(($CAPACITY+1))
DISPLAY=:0
update_keyboard_colour () {
        GREEN_LIMIT=80
        YELLOW_LIMIT=60
        ORANGE_LIMIT=40
        RED_LIMIT=20
        if [ $CAPACITY -ge $GREEN_LIMIT ]; then
                COLOUR="\x7C\xFC\x00"
        elif [ $CAPACITY -ge $YELLOW_LIMIT ]; then
                COLOUR="\xFF\x6A\x00"
        elif [ $CAPACITY -ge $ORANGE_LIMIT ]; then
                COLOUR="\xFF\x1F\x00"
        elif [ $CAPACITY -le $RED_LIMIT ]; then
                COLOUR="\xFF\x06\x06"
        fi
        sh $HOME/.scripts/keyboard-colour $COLOUR
}
while true; do
        CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
        update_keyboard_colour
        CHARGING=$(cat /sys/class/power_supply/BAT0/uevent | grep POWER_SUPPLY_STATUS)
        CHARGING=${CHARGING//POWER_SUPPLY_STATUS=/}
        if [[ $CHARGING = "Discharging" ]]; then
                if [ $CAPACITY -le $UPPER_LIMIT -a $CAPACITY -lt $PREVIOUS_CAPACITY ]; then
                        notify-send --urgency=critical "$MESSAGE | $CAPACITY%"
                        PREVIOUS_CAPACITY=$CAPACITY
                elif [ $CAPACITY -gt $UPPER_LIMIT ]; then
                        PREVIOUS_CAPACITY=$(($UPPER_LIMIT+1))
                fi
        else
                PREVIOUS_CAPACITY=$(($UPPER_LIMIT+1))
        fi
        sleep $POLL
done
