#!/bin/zsh
autoload +X _complete
autoload -U compinit && compinit
source /usr/bin/aws_zsh_completer.sh
functions[_original_complete]=$functions[_complete]
_complete () {
  unset 'compstate[vared]'
  _original_complete "$@"
}
FILTER=""
LINELIMIT="limit: 15"
DETAIL="list"
LONGLIMIT=1000
long_comparator=15
FOCUS=""
while true; do
        clear
        unbuffer task $FOCUS $DETAIL $FILTER $LINELIMIT | head -n $LONGLIMIT
        task calendar
        COMMAND=''
        vared COMMAND
        if [[ $COMMAND = "q" ]] || [[ $COMMAND = "Q" ]]
                then break
            else
                if [[ $COMMAND == "project:"* ]] then
                        if [[ $COMMAND == *"all"* ]] then
                                FILTER=""
                        else
                                FILTER=$COMMAND
                        fi
                elif [[ $COMMAND == "limit:"* ]] then
                        LINELIMIT=$COMMAND
                        CURRENTLIMIT=${COMMAND//limit:/}
                        if [[ $CURRENTLIMIT == *"all"* ]] then
                                LINELIMIT=$COMMAND
                                LONGLIMIT=1000
                        else
                                if [ "$CURRENTLIMIT" -le 15 ]
                                then
                                        LONGLIMIT=18
                                else
                                        LONGLIMIT=1000
                                fi
                        fi
                elif [[ $COMMAND == "focus:"* ]] then
                        if [[ $COMMAND == *"all"* ]] then
                                FOCUS=""
                        else
                                FOCUS=${COMMAND//focus:/}
                        fi
                elif [[ $COMMAND == "detail:"* ]] then
                        if [[ $COMMAND == *"long"* ]] then
                                DETAIL="long"
                                if [ "$LIMIT" -le 15 ]
                                then
                                        LONGLIMIT=18
                                else
                                        LONGLIMIT=1000
                                fi
                        else
                                DETAIL="list"
                                LONGLIMIT=1000
                        fi
                else
                       eval $COMMAND
                fi
        fi
done
