#!/bin/zsh
autoload +X _complete
autoload -U compinit && compinit
source /usr/bin/aws_zsh_completer.sh
functions[_original_complete]=$functions[_complete]
_complete () {
  unset 'compstate[vared]'
  _original_complete "$@"
}
trap ctrl_c INT
function ctrl_c() {
        echo "Please type 'q' or 'Q' to quit"
        return
}
function compute_line_limit(){
        eval $(xdotool getwindowgeometry -shell $(xdotool getactivewindow))
        let "ALLOWED_LINES = $HEIGHT / 27"
        LINE_LIMIT="$ALLOWED_LINES"
        PRINTED_LINES=$(unbuffer task $FOCUS $DETAIL $FILTER $DUE limit:$LINE_LIMIT | wc -l)
        if [ "$SHOW_CALENDAR" = true ]; then
                CALENDAR_LINES=$(task calendar | wc -l)
                let "PRINTED_LINES = $PRINTED_LINES + $CALENDAR_LINES"
        fi
        while [ "$PRINTED_LINES" -ge "$ALLOWED_LINES" ]; do
                let "LINE_LIMIT = $LINE_LIMIT - 1"
                PRINTED_LINES=$(unbuffer task $FOCUS $DETAIL $FILTER $DUE limit:$LINE_LIMIT | wc -l)
                if [ "$SHOW_CALENDAR" = true ]; then
                        CALENDAR_LINES=$(task calendar | wc -l)
                        let "PRINTED_LINES = $PRINTED_LINES + $CALENDAR_LINES"
                fi
        done
        LINE_LIMIT="limit:$LINE_LIMIT"
        return
}

re='^[0-9]+$'
FILTER=""
DETAIL="list"
# LONGLIMIT=1000
# LONGLIMIT_FIT=19
FOCUS=""
i3-msg title_format "Calendar"
DUE=""
HELP=0
SHOW_CALENDAR=false
PRIORITY=""
LIMIT_FIT=true
compute_line_limit
while true; do
        if [ "$LIMIT_FIT" = true ]; then
                compute_line_limit
        fi

        clear
        unbuffer task $DETAIL $LINE_LIMIT $FOCUS $FILTER $DUE $PRIORITY
        if [ "$SHOW_CALENDAR" = true ]; then
                task calendar
        else
                echo " "
        fi
        if [ $HELP -eq 1 ]; then
                echo "project:\ndue:\nlimit:\nfocus:\ndetail:\npriority:\ncalendar:"
                HELP=0
        fi
        COMMAND=''
        vared COMMAND
        if [[ $COMMAND = "q" ]] || [[ $COMMAND = "Q" ]]
                then break
            else
                if [[ $COMMAND == "project:"* ]] then
                        ALL_COMMAND=${COMMAND//project:/}
                        if [[ $ALL_COMMAND == *"all"* ]] then
                                FILTER=""
                        elif [[ $ALL_COMMAND == "" ]] then
                                FILTER=""
                        else
                                FILTER="\($COMMAND\)"
                        fi
                elif [[ $COMMAND == "help"* ]] then
                        HELP=1
                elif [[ $COMMAND == "due:"* ]] then
                        ALL_COMMAND=${COMMAND//due:/}
                        if [[ $ALL_COMMAND == *"all"* ]] then
                                DUE=""
                        elif [[ $ALL_COMMAND == "" ]] then
                                DUE=""
                        else
                                DUE="\($COMMAND\)"
                        fi
                elif [[ $COMMAND == "limit:"* ]] then
                        CURRENT_LIMIT=${COMMAND//limit:/}
                        LIMIT_FIT=false
                        if [[ $CURRENT_LIMIT =~ $re ]] ; then
                                LINE_LIMIT=$COMMAND
                        elif [[ $CURRENT_LIMIT == *"all"* ]] then
                                LINE_LIMIT=$COMMAND
                        elif [[ $CURRENT_LIMIT == *"fit"* ]] then
                                compute_line_limit
                                LIMIT_FIT=true
                        fi
                elif [[ $COMMAND == "focus:"* ]] then
                        if [[ $COMMAND == *"all"* ]] then
                                FOCUS=""
                        else
                                FOCUS=${COMMAND//focus:/}
                        fi
                elif [[ $COMMAND == "detail:"* ]] then
                        if [[ $COMMAND == *"long"* ]] then
                                DETAIL="long"
                        else
                                DETAIL="list"
                        fi
                elif [[ $COMMAND == "priority:"* ]] then
                        ALL_COMMAND=${COMMAND//priority:/}
                        if [[ $ALL_COMMAND == *"all"* ]] then
                                PRIORITY="\(priority:L or priority:M or priority:H\)"
                        # if [[ $COMMAND == *"L"* ]] then
                        #         PRIORITY="priority:L"
                        # elif [[ $COMMAND == *"M"* ]] then
                        #         PRIORITY="priority:M"
                        # elif [[ $COMMAND == *"H"* ]] then
                        #         PRIORITY="priority:H"
                        # elif [[ $COMMAND == *"all"* ]] then
                        #         PRIORITY="priority:L,M,H"
                        else
                                PRIORITY="\($COMMAND\)"
                        fi
                elif [[ $COMMAND == "calendar:"* ]] then
                        CALENDAR_STATE=${COMMAND//calendar:/}
                        if [[ $CALENDAR_STATE == *"off"* ]] then
                                SHOW_CALENDAR=false
                        elif [[ $CALENDAR_STATE == *"on"* ]] then
                                SHOW_CALENDAR=true
                        fi
                else
                       eval $COMMAND
                fi
        fi
done
