#!/bin/zsh
autoload +X _complete
autoload -U compinit && compinit
source /usr/bin/aws_zsh_completer.sh
functions[_original_complete]=$functions[_complete]
_complete () {
  unset 'compstate[vared]'
  _original_complete "$@"
}
trap ctrl_c INT
function ctrl_c() {
        echo "Please type 'q' or 'Q' to quit"
        return
}
function compute_line_limit(){
        eval $(xdotool getwindowgeometry -shell $(xdotool getactivewindow))
        let "ALLOWED_LINES = $HEIGHT / 31"
        LINE_LIMIT="$ALLOWED_LINES"
        PRINTED_LINES=$(unbuffer task $FOCUS $DETAIL $FILTER $DUE limit:$LINE_LIMIT | wc -l)
        while [ "$PRINTED_LINES" -ge "$ALLOWED_LINES" ]; do
                let "LINE_LIMIT = $LINE_LIMIT - 1"
                PRINTED_LINES=$(unbuffer task $FOCUS $DETAIL $FILTER $DUE limit:$LINE_LIMIT | wc -l)
        done
        LINE_LIMIT="limit: $LINE_LIMIT"
        return
}

re='^[0-9]+$'
FILTER=""
DETAIL="list"
# LONGLIMIT=1000
# LONGLIMIT_FIT=19
FOCUS=""
i3-msg title_format "Calendar"
DUE=""
HELP=0
SHOW_CALENDAR=false
compute_line_limit
while true; do
        clear
        unbuffer task $FOCUS $DETAIL $FILTER $DUE $LINE_LIMIT # | head -n $LONGLIMIT
        if [ "$SHOW_CALENDAR" = true ]; then
                task calendar
        else
                echo " "
        fi
        if [ $HELP -eq 1 ]; then
                echo "project:\ndue:\nlimit:\nfocus:\ndetail:"
                HELP=0
        fi
        COMMAND=''
        vared COMMAND
        if [[ $COMMAND = "q" ]] || [[ $COMMAND = "Q" ]]
                then break
            else
                if [[ $COMMAND == "project:"* ]] then
                        if [[ $COMMAND == *"all"* ]] then
                                FILTER=""
                        else
                                FILTER=$COMMAND
                        fi
                elif [[ $COMMAND == "help"* ]] then
                        HELP=1
                elif [[ $COMMAND == "due:"* ]] then
                        if [[ $COMMAND == *"all"* ]] then
                                DUE=""
                        else
                                DUE=$COMMAND
                        fi
                elif [[ $COMMAND == "limit:"* ]] then
                        CURRENT_LIMIT=${COMMAND//limit:/}
                        if [[ $CURRENT_LIMIT =~ $re ]] ; then
                                LINE_LIMIT=$COMMAND
                        fi
                        if [[ $CURRENT_LIMIT == *"all"* ]] then
                                LINE_LIMIT=$COMMAND
                        elif [[ $CURRENT_LIMIT == *"fit"* ]] then
                                compute_line_limit
                        fi
                elif [[ $COMMAND == "focus:"* ]] then
                        if [[ $COMMAND == *"all"* ]] then
                                FOCUS=""
                        else
                                FOCUS=${COMMAND//focus:/}
                        fi
                elif [[ $COMMAND == "detail:"* ]] then
                        if [[ $COMMAND == *"long"* ]] then
                                DETAIL="long"
                        else
                                DETAIL="list"
                        fi
                elif [[ $COMMAND == "calendar:"* ]] then
                        CALENDAR_STATE=${COMMAND//calendar:/}
                        if [[ $CALENDAR_STATE == *"off"* ]] then
                                SHOW_CALENDAR=false
                        elif [[ $CALENDAR_STATE == *"on"* ]] then
                                SHOW_CALENDAR=true
                        fi
                else
                       eval $COMMAND
                fi
        fi
done
