#!/usr/bin/env python3
import subprocess
import io


def connect_wifi():
    command = ['wpa_cli', '-i', 'wlp2s0']
    print('Available networks...')
    results = subprocess.Popen(command +
                               ['scan', ';'
                                'sleep', '1', ';'] +
                               command + ['scan_results'],
                               stdout=subprocess.PIPE,)
    results = subprocess.Popen(command +
                               ['scan', ';'
                                'sleep', '1', ';'] +
                               command + ['scan_results'],
                               stdout=subprocess.PIPE,)
    for line in io.TextIOWrapper(results.stdout, encoding="utf-8"):
        # do something with linerint(results.stdout.readlines())
        print(line)
        ssid = input('Network SSID: ')


if __name__ == "__main__":
    connect_wifi()
