#!/bin/sh
echo 'opening output ports'
open_output_ports

while true; do
        read -p '[r]ight | [l]eft | [m]irror | [n]one > ' MODE
        PRODUCTIVE_POLYBAR=$(cat $HOME/.config/scripts/productive_polybar_status)
        if [ "$PRODUCTIVE_POLYBAR" == "on" ]; then
                LAUNCH_TYPE="launch_productive"
        else
                LAUNCH_TYPE="launch"
        fi
        case $MODE in
                [rR])
                        echo 'displaying right...'
                        xrandr --output VIRTUAL1 --auto --right-of eDP1
                        polybar-rebar-wrapper $LAUNCH_TYPE
                        fehbg
                        break
                        ;;
                [lL])
                        echo 'displaying left...'
                        xrandr --output VIRTUAL1 --auto --left-of eDP1
                        polybar-rebar-wrapper $LAUNCH_TYPE
                        fehbg
                        break
                        ;;
                [mM])
                        echo 'mirroring display...'
                        xrandr --output VIRTUAL1 --auto --same-as eDP1
                        polybar-rebar-wrapper $LAUNCH_TYPE
                        fehbg
                        break
                        ;;
                [nM])
                        echo 'exiting...'
                        xrandr --output VIRTUAL1 --off
                        polybar-rebar-wrapper $LAUNCH_TYPE
                        fehbg
                        exit 1
                        ;;
                *)
                        echo 'invalid choice'
        esac
done
