#!/bin/sh
echo 'opening output ports'
open_output_ports

while true; do
        read -p '[r]ight | [l]eft | [m]irror | [n]one > ' MODE
        case $MODE in
                [rR])
                        echo 'displaying right...'
                        xrandr --output VIRTUAL1 --auto --right-of eDP1
                        polybar_rebar
                        fehbg
                        break
                        ;;
                [lL])
                        echo 'displaying left...'
                        xrandr --output VIRTUAL1 --auto --left-of eDP1
                        polybar_rebar
                        fehbg
                        break
                        ;;
                [mM])
                        echo 'mirroring display...'
                        xrandr --output VIRTUAL1 --auto --same-as eDP1
                        polybar_rebar
                        fehbg
                        break
                        ;;
                [nM])
                        echo 'exiting...'
                        xrandr --output VIRTUAL1 --off
                        polybar_rebar
                        fehbg
                        exit 1
                        ;;
                *)
                        echo 'invalid choice'
        esac
done
