#!/bin/bash
export PATH=$PATH:$HOME/.scripts

# default monitor is LVDS1
MONITOR=eDP1

# Note that HDMI=VIRTUAL1 due to intel-virtual-output and dual-gpus on my machine
function ActivateHDMI {
    # echo "Switching to HDMI"
    # open_output_ports
    # xrandr --output VIRTUAL1 --auto --right-of eDP1
    # polybar_rebar
    # fehbg
    echo $HDMI_ORIENTATION_STATUS | display_hdmi
    MONITOR=HDMI
}
function DeactivateHDMI {
    # echo "Switching to eDP1"
    # xrandr --output VIRTUAL1 --off
    # polybar_rebar
    # fehbg
    # echo $HDMI_ORIENTATION_STATUS | display_hdmi
    xrandr --output VIRTUAL1 --off
    MONITOR=eDP1
}

# functions to check if HDMI is connected and in use
function HDMIActive {
    [ $MONITOR = "HDMI" ]
}
function HDMIConnected {
    ! xrandr | grep "^VIRTUAL1" | grep disconnected
}

function OrientHDMIRight {
    xrandr --output VIRTUAL1 --auto --right-of eDP1
    polybar_rebar
    fehbg
    echo "r" > $HOME/.status-files/hdmi_orientation_status
}
function OrientHDMILeft {
    xrandr --output VIRTUAL1 --auto --left-of eDP1
    polybar_rebar
    fehbg
    echo "l" > $HOME/.status-files/hdmi_orientation_status
}
function OrientHDMIMirror {
    xrandr --output VIRTUAL1 --auto --same-as eDP1
    polybar_rebar
    fehbg
    echo "m" > $HOME/.status-files/hdmi_orientation_status
}
function OrientHDMINone {
    xrandr --output VIRTUAL1 --off
    polybar_rebar
    fehbg
    echo "n" > $HOME/.status-files/hdmi_orientation_status
}
while true; do
        read HDMI_ORIENTATION_STATUS < $HOME/.status-files/hdmi_orientation_status
        read NEW_HDMI_ORIENTATION_STATUS < $HOME/.status-files/new_hdmi_orientation_status
        if ! HDMIActive && ! HDMIConnected
        then
        echo "not connected not active"
        fi

        if ! HDMIActive && HDMIConnected
        then
        echo "connected not active"
            ActivateHDMI
        fi

        if HDMIActive && ! HDMIConnected
        then
        echo "not connected active"
            DeactivateHDMI
        fi

        if HDMIActive && HDMIConnected
        then
                echo "active and conncetd"
            if [ "$HDMI_ORIENTATION_STATUS" != "r" ] && [ "$NEW_HDMI_ORIENTATION_STATUS" = "r" ]
            then
                    echo "R"
                OrientHDMIRight
            fi

            if [ "$HDMI_ORIENTATION_STATUS" != "l" ] && [ "$NEW_HDMI_ORIENTATION_STATUS" = "l" ]
            then
                    echo "L"
                OrientHDMILeft
            fi

            if [ "$HDMI_ORIENTATION_STATUS" != "m" ] && [ "$NEW_HDMI_ORIENTATION_STATUS" = "m" ]
            then
                    echo "M"
                OrientHDMIMirror
            fi

            if [ "$HDMI_ORIENTATION_STATUS" != "n" ] && [ "$NEW_HDMI_ORIENTATION_STATUS" = "n" ]
            then
                    echo "N"
                OrientHDMINone
            fi
        fi
        sleep 2s
done
