#!/bin/sh
while getopts i: option
do
case "${option}"
in
i) INFO=${OPTARG};;
esac
done


case $INFO in
        staged) echo $(git dotfiles diff --name-only --cached | wc -l);;
        modified) echo $(git dotfiles ls-files $HOME --modified | wc -l);;
        deleted) echo $(git dotfiles ls-files $HOME --deleted | wc -l);;
        ahead) echo $(git dotfiles rev-list razer-laptop...origin/razer-laptop --count);;
        *) echo "??";;
esac
