#!/bin/sh
while getopts i: option
do
case "${option}"
in
i) INFO=${OPTARG};;
esac
done
get_icon() {
    case $1 in
        01d) icon="";;
        01n) icon="";;
        02d) icon="";;
        02n) icon="";;
        03*) icon="";;
        04*) icon="";;
        09d) icon="";;
        09n) icon="";;
        10d) icon="";;
        10n) icon="";;
        11d) icon="";;
        11n) icon="";;
        13d) icon="";;
        13n) icon="";;
        50d) icon="";;
        50n) icon="";;
        *) icon="";
    esac

    echo $icon
}

get_duration() {

    osname=$(uname -s)

    case $osname in
        *BSD) date -r "$1" -u +%H:%M;;
        *) date --date="@$1" -u +%H:%M;;
    esac

}

KEY=""
CITY="Ottawa"
UNITS="metric"
SYMBOL="°"

API="https://api.openweathermap.org/data/2.5"
case $INFO in
    current)
        if [ -n "$CITY" ]; then
            if [ "$CITY" -eq "$CITY" ] 2>/dev/null; then
                CITY_PARAM="id=$CITY"
            else
                CITY_PARAM="q=$CITY"
            fi

            current=$(curl -sf "$API/weather?appid=$KEY&$CITY_PARAM&units=$UNITS")
            forecast=$(curl -sf "$API/forecast?appid=$KEY&$CITY_PARAM&units=$UNITS&cnt=1")
        else
            location=$(curl -sf https://location.services.mozilla.com/v1/geolocate?key=geoclue)

            if [ -n "$location" ]; then
                location_lat="$(echo "$location" | jq '.location.lat')"
                location_lon="$(echo "$location" | jq '.location.lng')"

                current=$(curl -sf "$API/weather?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS")
                forecast=$(curl -sf "$API/forecast?appid=$KEY&lat=$location_lat&lon=$location_lon&units=$UNITS&cnt=1")
            fi
        fi

        if [ -n "$current" ] && [ -n "$forecast" ]; then
            current_temp=$(echo "$current" | jq ".main.temp" | cut -d "." -f 1)
            current_icon=$(echo "$current" | jq -r ".weather[0].icon")

            forecast_temp=$(echo "$forecast" | jq ".list[].main.temp" | cut -d "." -f 1)
            forecast_icon=$(echo "$forecast" | jq -r ".list[].weather[0].icon")


            if [ "$current_temp" -gt "$forecast_temp" ]; then
                trend=""
            elif [ "$forecast_temp" -gt "$current_temp" ]; then
                trend=""
            else
                trend=""
            fi


            sun_rise=$(echo "$current" | jq ".sys.sunrise")
            sun_set=$(echo "$current" | jq ".sys.sunset")
            now=$(date +%s)

            if [ "$sun_rise" -gt "$now" ]; then
                daytime_icon=""
                daytime="$(get_duration "$((sun_rise-now))")"
            elif [ "$sun_set" -gt "$now" ]; then
                daytime_icon=""
                daytime="$(get_duration "$((sun_set-now))")"
            else
                daytime_icon=""
                daytime="$(get_duration "$((sun_rise-now))")"
            fi

            # echo "$(get_icon "$current_icon") $current_temp$SYMBOL  $trend  $(get_icon "$forecast_icon") $forecast_temp$SYMBOL   $daytime"
            # case $INFO in
            #     current) echo "$current_temp$SYMBOL";;
            #     current_icon) echo "$(get_icon "$current_icon")";;
            #     forecast) echo "$forecast_temp$SYMBOL";;
            #     forecast_icon) echo "$(get_icon "$forecast_icon")";;
            #     trend) echo "$trend";;
            #     set) echo "$daytime";;
            #     set_icon) echo "$daytime_icon";;
            #     *) echo "wrong ";;
            # esac
            echo "$current_temp$SYMBOL"
            echo "$(get_icon "$current_icon")" > $HOME/.config/polybar/modules/weather/current_temp_icon
            echo "$forecast_temp$SYMBOL" > $HOME/.config/polybar/modules/weather/forecast_temp
            echo "$(get_icon "$forecast_icon")" > $HOME/.config/polybar/modules/weather/forecase_temp_icon
            echo "$trend" > $HOME/.config/polybar/modules/weather/trend
            echo "$daytime" > $HOME/.config/polybar/modules/weather/daytime
            echo "$daytime_icon" > $HOME/.config/polybar/modules/weather/daytime_icon
        else
            echo "?"
            echo "$(get_icon "$current_icon")" > $HOME/.config/polybar/modules/weather/current_temp_icon
            echo "?" > $HOME/.config/polybar/modules/weather/forecast_temp
            echo "$(get_icon "$forecast_icon")" > $HOME/.config/polybar/modules/weather/forecase_temp_icon
            echo "$trend" > $HOME/.config/polybar/modules/weather/trend
            echo "?" > $HOME/.config/polybar/modules/weather/daytime
            daytime_icon=""
            echo "$daytime_icon" > $HOME/.config/polybar/modules/weather/daytime_icon
            # case $INFO in
            #     current) echo "?";;
            #     current_icon) echo "$(get_icon "$current_icon")";;
            #     forecast) echo "?";;
            #     forecast_icon) echo "$(get_icon "$forecast_icon")";;
            #     trend) echo "$trend";;
            #     set) echo "?";;
            #     set_icon) daytime_icon=""; echo "$daytime_icon";;
            #     *) echo "***";;
            # esac
        fi
        ;;
    current_icon) cat $HOME/.config/polybar/modules/weather/current_temp_icon;;
    forecast) cat $HOME/.config/polybar/modules/weather/forecast_temp;;
    forecast_icon) cat $HOME/.config/polybar/modules/weather/forecase_temp_icon;;
    trend) cat $HOME/.config/polybar/modules/weather/trend;;
    set) cat $HOME/.config/polybar/modules/weather/daytime;;
    set_icon) cat $HOME/.config/polybar/modules/weather/daytime_icon;;
    *) echo "*";;
esac
