#!/bin/sh
# TODO
# NOTE: polybar can output the WM window id, by calling
# polybar *BAR NAME* -w
# for example, `polybar file-sync-panel -w` outputs polybar-file-sync-panel_eDP1
# Then you can use `xdotool search --name polybar-file-sync-panel_eDP1` to get the window id, which you need to then raise

launch() {
    echo "close" > /tmp/polybar_side_panel_state
    echo "off" > $HOME/.config/scripts/productive_polybar_status
    killall -q polybar
    if type "xrandr"; then
        for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
            MONITOR=$m polybar --reload top&
            # MONITOR=$m polybar --reload bottom&
            # MONITOR=$m polybar --reload main-bottom&
        done
    else
        polybar --reload i3&
        # polybar --reload main-bottom&
    fi
}

launch_productive() {
    echo "on" > $HOME/.config/scripts/productive_polybar_status
    echo "close" > /tmp/polybar_side_panel_state
    killall -q polybar
    if type "xrandr"; then
        for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
            MONITOR=$m polybar --reload main-productive&
        done
    else
        polybar --reload main-productive&
    fi
}


case "$1" in
    launch)
        launch;;
    launch_productive)
        launch_productive;;
esac
