#!/usr/bin/env bash
# [COLORS]
alias diff='diff --color=always'
alias dmesg='dmesg --color=always'
alias grep='grep --color=always'
alias ls='ls --color -h'
alias less='less -R'
alias aws='aws --color on'
alias pacman='pacman --color=always'
alias ip='ip -c'
alias tshark='tshark --color'
export LESS=-R
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin bold
export LESS_TERMCAP_md=$'\E[1;36m'     # begin blink
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;44;30m' # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

man() {
    LESS_TERMCAP_md=$'\e[01;36m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;30m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

# ow is for those full access directories
export LS_COLORS='ow=4;34:*.py=0;35'

# PSQL related
# export ORANGE=`echo -e '\033[1;33m'`
# export GREEN=`echo -e '\033[1;36m'`
# export NO_COLOR=`echo -e '\033[0m'`
# export LESS="-iMSx4 -FXR"
# PAGER="sed \"s/\([[:space:]]\+[0-9.\-]\+\)$/${GREEN}\1$NO_COLOR/;"
# PAGER+="s/\([[:space:]]\+[0-9.\-]\+[[:space:]]\)/${GREEN}\1$NO_COLOR/g;"
# PAGER+="s/|/$ORANGE|$NO_COLOR/g;s/^\([-+]\+\)/$ORANGE\1$NO_COLOR/\" 2>/dev/null  | less"
# export PAGER
#
#
