#!/usr/bin/env bash
# [POWERLEVEL9k]
# FOR COLORS LIST
# UNCOMMENT alias term_colors='for code ({000..255}) print -P -- "$code: %F{$code}This is how your text would look like%f"'
# ALSO TO CHANGE COLORS
# POWERLEVEL9K_<name-of-segment>_<state>_[BACKGROUND|FOREGROUND]
# Segment		|	States
# -----------------------------------------------------------
# battery		|	LOW, CHARGING, CHARGED, DISCONNECTED
# context		|	DEFAULT, ROOT, SUDO, REMOTE, REMOTE_SUDO
# dir			|	HOME, HOME_SUBFOLDER, DEFAULT, ETC
# dir_writable		|	FORBIDDEN
# disk_usage		|	NORMAL, WARNING, CRITICAL
# host			|	LOCAL, REMOTE
# load			|	CRITICAL, WARNING, NORMAL
# rspec_stats		|	STATS_GOOD, STATS_AVG, STATS_BAD
# status		|	ERROR, OK (note: only, if verbose is not false)
# symfony2_tests	|	TESTS_GOOD, TESTS_AVG, TESTS_BAD
# user			|	DEFAULT, SUDO, ROOT
# vcs			|	CLEAN, UNTRACKED, MODIFIED
# vi_mode		|	NORMAL, INSERT
# source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme
#
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi
#
# UNCOMENT IF USING if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
# UNCOMENT IF USING   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# UNCOMENT IF USING fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# UNCOMMENT IF USING [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# UNCOMMENT IF USING source $HOME/.powerlevel10k/powerlevel10k.zsh-theme
